import { readdirSync, readFileSync, statSync } from 'node:fs';
import { join } from 'node:path';
import { fileURLToPath } from 'node:url';
import { describe, expect, it } from 'vitest';

const SRC = fileURLToPath(new URL('..', import.meta.url));

/**
 * Where a colour is allowed to be written down:
 *  - the token layer itself,
 *  - `palette.ts`, which Monaco reads because its theme API cannot take a
 *    variable, and which `palette.test.ts` keeps in step with the token layer,
 *  - `components/ui/*`, which is generated by the shadcn CLI and regenerated by
 *    it; the generated components already read tokens, and hand-editing them
 *    would be undone by the next `shadcn add`.
 */
const ALLOWED = ['theme/tokens.css', 'theme/palette.ts', 'components/ui/'];

const COLOUR =
  /(?<![\w-])(#[0-9a-fA-F]{3,8}\b|\brgba?\(\s*\d|\bhsla?\(\s*\d)/;

function files(dir: string): string[] {
  return readdirSync(dir).flatMap((name) => {
    const full = join(dir, name);
    if (name === 'node_modules') return [];
    return statSync(full).isDirectory() ? files(full) : [full];
  });
}

/** Strip comments so prose about a colour is not mistaken for a colour. */
function code(source: string): string {
  return source
    .replace(/\/\*[\s\S]*?\*\//g, '')
    .replace(/(^|[^:])\/\/.*$/gm, '$1');
}

describe('colour lives only in the token layer', () => {
  it('has no colour literal anywhere else', () => {
    const offenders: string[] = [];
    for (const file of files(SRC)) {
      if (!/\.(ts|tsx|css)$/.test(file) || /\.test\.tsx?$/.test(file)) continue;
      const rel = file.slice(SRC.length);
      if (ALLOWED.some((allowed) => rel.startsWith(allowed))) continue;

      code(readFileSync(file, 'utf8'))
        .split('\n')
        .forEach((line, i) => {
          if (COLOUR.test(line)) offenders.push(`${rel}:${i + 1}  ${line.trim()}`);
        });
    }
    expect(offenders, `colour literals outside the token layer:\n${offenders.join('\n')}`)
      .toEqual([]);
  });
});
