<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFrameworks>net8.0;net9.0;net10.0</TargetFrameworks>

    <IsPackable>false</IsPackable>

    <RootNamespace>ClrKernel</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="18.8.1" />
    <PackageReference Include="MSTest.TestAdapter" Version="4.3.3" />
    <PackageReference Include="MSTest.TestFramework" Version="4.3.3" />
    <PackageReference Include="Microsoft.Data.Sqlite" Version="8.0.10" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\ClrKernel.Core\ClrKernel.Core.csproj" />
    <ProjectReference Include="..\..\src\ClrKernel.Http\ClrKernel.Http.csproj" />
    <ProjectReference Include="..\..\src\ClrKernel.Mermaid\ClrKernel.Mermaid.csproj" />
    <ProjectReference Include="..\..\src\ClrKernel.PowerShell\ClrKernel.PowerShell.csproj" />
    <ProjectReference Include="..\..\src\ClrKernel.Sql\ClrKernel.Sql.csproj" />
    <ProjectReference Include="..\..\src\ClrKernel.Data\ClrKernel.Data.csproj" />
    <ProjectReference Include="..\..\src\ClrKernel.Data.Oracle\ClrKernel.Data.Oracle.csproj" />
    <ProjectReference Include="..\..\src\ClrKernel.Data.Odbc\ClrKernel.Data.Odbc.csproj" />
    <ProjectReference Include="..\..\src\ClrKernel.AnalysisServices\ClrKernel.AnalysisServices.csproj" />
    <ProjectReference Include="..\..\src\ClrKernel.Fabric\ClrKernel.Fabric.csproj" />
    <ProjectReference Include="..\..\src\ClrKernel.Primitives\ClrKernel.Primitives.csproj" />
    <ProjectReference Include="..\..\src\ClrKernel.Runner\ClrKernel.Runner.csproj" />
    <ProjectReference Include="..\..\src\ClrKernel.LanguageServices\ClrKernel.LanguageServices.csproj" />
  </ItemGroup>

</Project>
