<Project>
    <PropertyGroup>
        <Version>0.3.0</Version>
        <Company>ClrKernel</Company>
        <Product>ClrKernel</Product>
        <Authors>Jeremy Adams, Dan Shryock</Authors>
        <TargetFramework>net8.0</TargetFramework>
        <RollForward>Major</RollForward>
    </PropertyGroup>
</Project>
