// <auto-generated />
using System;
using ClrKernel.Studio;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace ClrKernel.Studio.Store.Migrations.Postgres
{
    [DbContext(typeof(PostgresRunsDbContext))]
    [Migration("20260828012544_AddRunActor")]
    partial class AddRunActor
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ClrKernel.Studio.AuthSession", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<DateTime>("LastSeenAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_seen_at");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("sessions", (string)null);
                });

            modelBuilder.Entity("ClrKernel.Studio.Credential", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("id");

                    b.Property<Guid>("AaGuid")
                        .HasColumnType("uuid")
                        .HasColumnName("aaguid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTime?>("LastUsedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_used_at");

                    b.Property<string>("Name")
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("name");

                    b.Property<byte[]>("PublicKey")
                        .IsRequired()
                        .HasColumnType("bytea")
                        .HasColumnName("public_key");

                    b.Property<long>("SignCount")
                        .HasColumnType("bigint")
                        .HasColumnName("sign_count");

                    b.Property<string>("Transports")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("transports");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("credentials", (string)null);
                });

            modelBuilder.Entity("ClrKernel.Studio.Invite", b =>
                {
                    b.Property<string>("Code")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("code");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<string>("Label")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("label");

                    b.Property<bool>("Revoked")
                        .HasColumnType("boolean")
                        .HasColumnName("revoked");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("role");

                    b.Property<DateTime?>("UsedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("used_at");

                    b.Property<Guid?>("UsedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("used_by");

                    b.HasKey("Code");

                    b.ToTable("invites", (string)null);
                });

            modelBuilder.Entity("ClrKernel.Studio.JobTriggerState", b =>
                {
                    b.Property<string>("Project")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("project");

                    b.Property<string>("Environment")
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("environment");

                    b.Property<string>("JobName")
                        .HasColumnType("text")
                        .HasColumnName("job_name");

                    b.Property<DateTime>("LastTriggerAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_trigger_at");

                    b.HasKey("Project", "Environment", "JobName");

                    b.ToTable("job_trigger_state", (string)null);
                });

            modelBuilder.Entity("ClrKernel.Studio.ManualRun", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("ActorId")
                        .HasColumnType("uuid")
                        .HasColumnName("actor_id");

                    b.Property<string>("ActorName")
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("actor_name");

                    b.Property<int>("CellCount")
                        .HasColumnType("integer")
                        .HasColumnName("cell_count");

                    b.Property<string>("Cells")
                        .HasColumnType("text")
                        .HasColumnName("cells");

                    b.Property<string>("Environment")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("environment");

                    b.Property<string>("ErrorSummary")
                        .HasColumnType("text")
                        .HasColumnName("error_summary");

                    b.Property<DateTime?>("FinishedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("finished_at");

                    b.Property<string>("NotebookPath")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("notebook_path");

                    b.Property<string>("Outcome")
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("outcome");

                    b.Property<string>("Overrides")
                        .HasColumnType("text")
                        .HasColumnName("overrides");

                    b.Property<string>("Project")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("project");

                    b.Property<DateTime>("StartedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("started_at");

                    b.HasKey("Id");

                    b.HasIndex("StartedAt");

                    b.HasIndex("Project", "Environment", "NotebookPath");

                    b.ToTable("manual_runs", (string)null);
                });

            modelBuilder.Entity("ClrKernel.Studio.ProjectMembership", b =>
                {
                    b.Property<string>("ProjectSlug")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("project");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(24)
                        .HasColumnType("character varying(24)")
                        .HasColumnName("role");

                    b.HasKey("ProjectSlug", "UserId");

                    b.HasIndex("UserId");

                    b.ToTable("project_members", (string)null);
                });

            modelBuilder.Entity("ClrKernel.Studio.PromotionAudit", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("ActorId")
                        .HasColumnType("uuid")
                        .HasColumnName("actor_id");

                    b.Property<string>("ActorName")
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("actor_name");

                    b.Property<string>("CommitSha")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("commit_sha");

                    b.Property<string>("EvidenceRuns")
                        .HasColumnType("text")
                        .HasColumnName("evidence_runs");

                    b.Property<bool>("IsDeletion")
                        .HasColumnType("boolean")
                        .HasColumnName("is_deletion");

                    b.Property<string>("Paths")
                        .HasColumnType("text")
                        .HasColumnName("paths");

                    b.Property<string>("Project")
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("project");

                    b.Property<DateTime>("PromotedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("promoted_at");

                    b.Property<string>("Unscheduled")
                        .HasColumnType("text")
                        .HasColumnName("unscheduled");

                    b.HasKey("Id");

                    b.HasIndex("Project");

                    b.HasIndex("PromotedAt");

                    b.ToTable("promotions", (string)null);
                });

            modelBuilder.Entity("ClrKernel.Studio.QueryAudit", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("ActorId")
                        .HasColumnType("uuid")
                        .HasColumnName("actor_id");

                    b.Property<string>("ActorName")
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("actor_name");

                    b.Property<string>("ConnectionId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("connection_id");

                    b.Property<string>("ConnectionName")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("connection_name");

                    b.Property<double>("DurationMs")
                        .HasColumnType("double precision")
                        .HasColumnName("duration_ms");

                    b.Property<string>("ErrorSummary")
                        .HasColumnType("text")
                        .HasColumnName("error_summary");

                    b.Property<bool>("LeastPrivilege")
                        .HasColumnType("boolean")
                        .HasColumnName("least_privilege");

                    b.Property<string>("Outcome")
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("outcome");

                    b.Property<int>("RowsAffected")
                        .HasColumnType("integer")
                        .HasColumnName("rows_affected");

                    b.Property<string>("Scope")
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("scope");

                    b.Property<DateTime>("StartedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("started_at");

                    b.Property<string>("Statement")
                        .HasColumnType("text")
                        .HasColumnName("statement");

                    b.HasKey("Id");

                    b.HasIndex("ConnectionId");

                    b.HasIndex("StartedAt");

                    b.ToTable("connection_queries", (string)null);
                });

            modelBuilder.Entity("ClrKernel.Studio.Run", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid?>("ActorId")
                        .HasColumnType("uuid")
                        .HasColumnName("actor_id");

                    b.Property<string>("ActorName")
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("actor_name");

                    b.Property<string>("ArtifactPath")
                        .HasColumnType("text")
                        .HasColumnName("artifact_path");

                    b.Property<int>("Attempt")
                        .HasColumnType("integer")
                        .HasColumnName("attempt");

                    b.Property<Guid?>("CausedByRunId")
                        .HasColumnType("uuid")
                        .HasColumnName("caused_by_run_id");

                    b.Property<string>("CommitSha")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("commit_sha");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Environment")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("environment");

                    b.Property<string>("ErrorSummary")
                        .HasColumnType("text")
                        .HasColumnName("error_summary");

                    b.Property<DateTime?>("FinishedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("finished_at");

                    b.Property<bool>("HadOverrides")
                        .HasColumnType("boolean")
                        .HasColumnName("had_overrides");

                    b.Property<string>("JobName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("job_name");

                    b.Property<string>("LogPath")
                        .HasColumnType("text")
                        .HasColumnName("log_path");

                    b.Property<string>("NotebookPath")
                        .HasColumnType("text")
                        .HasColumnName("notebook_path");

                    b.Property<string>("Project")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("project");

                    b.Property<DateTime?>("ScheduledFor")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("scheduled_for");

                    b.Property<DateTime?>("StartedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("started_at");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("status");

                    b.Property<string>("Trigger")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("trigger_type");

                    b.Property<bool>("WasDirty")
                        .HasColumnType("boolean")
                        .HasColumnName("was_dirty");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("Project", "Environment", "JobName");

                    b.ToTable("runs", (string)null);
                });

            modelBuilder.Entity("ClrKernel.Studio.RunCell", b =>
                {
                    b.Property<Guid>("RunId")
                        .HasColumnType("uuid")
                        .HasColumnName("run_id");

                    b.Property<int>("CellIndex")
                        .HasColumnType("integer")
                        .HasColumnName("cell_index");

                    b.Property<string>("ErrorSummary")
                        .HasColumnType("text")
                        .HasColumnName("error_summary");

                    b.Property<DateTime?>("FinishedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("finished_at");

                    b.Property<string>("SourcePreview")
                        .HasColumnType("text")
                        .HasColumnName("source_preview");

                    b.Property<DateTime?>("StartedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("started_at");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("status");

                    b.HasKey("RunId", "CellIndex");

                    b.ToTable("run_cells", (string)null);
                });

            modelBuilder.Entity("ClrKernel.Studio.SavedQuery", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("ConnectionId")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("connection_id");

                    b.Property<string>("ConnectionName")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("connection_name");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<string>("CreatedByName")
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("created_by_name");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<Guid?>("OwnerId")
                        .HasColumnType("uuid")
                        .HasColumnName("owner_id");

                    b.Property<string>("Scope")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("scope");

                    b.Property<string>("Sql")
                        .HasColumnType("text")
                        .HasColumnName("sql");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("Scope", "OwnerId");

                    b.ToTable("saved_queries", (string)null);
                });

            modelBuilder.Entity("ClrKernel.Studio.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<bool>("Disabled")
                        .HasColumnType("boolean")
                        .HasColumnName("disabled");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("display_name");

                    b.Property<DateTime?>("LastSeenAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_seen_at");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("role");

                    b.HasKey("Id");

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("ClrKernel.Studio.Credential", b =>
                {
                    b.HasOne("ClrKernel.Studio.User", "User")
                        .WithMany("Credentials")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("ClrKernel.Studio.ProjectMembership", b =>
                {
                    b.HasOne("ClrKernel.Studio.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ClrKernel.Studio.User", b =>
                {
                    b.Navigation("Credentials");
                });
#pragma warning restore 612, 618
        }
    }
}
