// <auto-generated />
using System;
using ClrKernel.Jobs;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ClrKernel.Jobs.Store.Migrations.SqlServer
{
    [DbContext(typeof(SqlServerRunsDbContext))]
    [Migration("20260818225232_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ClrKernel.Jobs.JobTriggerState", b =>
                {
                    b.Property<string>("JobName")
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("job_name");

                    b.Property<DateTime>("LastTriggerAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("last_trigger_at");

                    b.HasKey("JobName");

                    b.ToTable("job_trigger_state", (string)null);
                });

            modelBuilder.Entity("ClrKernel.Jobs.Run", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<string>("ArtifactPath")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("artifact_path");

                    b.Property<int>("Attempt")
                        .HasColumnType("int")
                        .HasColumnName("attempt");

                    b.Property<Guid?>("CausedByRunId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("caused_by_run_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at");

                    b.Property<string>("ErrorSummary")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("error_summary");

                    b.Property<DateTime?>("FinishedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("finished_at");

                    b.Property<string>("JobName")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("job_name");

                    b.Property<string>("LogPath")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("log_path");

                    b.Property<string>("NotebookPath")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("notebook_path");

                    b.Property<DateTime?>("ScheduledFor")
                        .HasColumnType("datetime2")
                        .HasColumnName("scheduled_for");

                    b.Property<DateTime?>("StartedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("started_at");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("nvarchar(16)")
                        .HasColumnName("status");

                    b.Property<string>("Trigger")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("nvarchar(16)")
                        .HasColumnName("trigger_type");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("JobName");

                    b.ToTable("runs", (string)null);
                });

            modelBuilder.Entity("ClrKernel.Jobs.RunCell", b =>
                {
                    b.Property<Guid>("RunId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("run_id");

                    b.Property<int>("CellIndex")
                        .HasColumnType("int")
                        .HasColumnName("cell_index");

                    b.Property<string>("ErrorSummary")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("error_summary");

                    b.Property<DateTime?>("FinishedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("finished_at");

                    b.Property<string>("SourcePreview")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("source_preview");

                    b.Property<DateTime?>("StartedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("started_at");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("nvarchar(16)")
                        .HasColumnName("status");

                    b.HasKey("RunId", "CellIndex");

                    b.ToTable("run_cells", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
