// <auto-generated />
using System;
using ClrKernel.Jobs;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ClrKernel.Jobs.Store.Migrations.SqlServer
{
    [DbContext(typeof(SqlServerRunsDbContext))]
    partial class SqlServerRunsDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ClrKernel.Jobs.AuthSession", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("expires_at");

                    b.Property<DateTime>("LastSeenAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("last_seen_at");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("sessions", (string)null);
                });

            modelBuilder.Entity("ClrKernel.Jobs.Credential", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)")
                        .HasColumnName("id");

                    b.Property<Guid>("AaGuid")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("aaguid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at");

                    b.Property<DateTime?>("LastUsedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("last_used_at");

                    b.Property<string>("Name")
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)")
                        .HasColumnName("name");

                    b.Property<byte[]>("PublicKey")
                        .IsRequired()
                        .HasColumnType("varbinary(max)")
                        .HasColumnName("public_key");

                    b.Property<long>("SignCount")
                        .HasColumnType("bigint")
                        .HasColumnName("sign_count");

                    b.Property<string>("Transports")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)")
                        .HasColumnName("transports");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("credentials", (string)null);
                });

            modelBuilder.Entity("ClrKernel.Jobs.Invite", b =>
                {
                    b.Property<string>("Code")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)")
                        .HasColumnName("code");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("created_by");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("expires_at");

                    b.Property<string>("Label")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("label");

                    b.Property<bool>("Revoked")
                        .HasColumnType("bit")
                        .HasColumnName("revoked");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("nvarchar(16)")
                        .HasColumnName("role");

                    b.Property<DateTime?>("UsedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("used_at");

                    b.Property<Guid?>("UsedBy")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("used_by");

                    b.HasKey("Code");

                    b.ToTable("invites", (string)null);
                });

            modelBuilder.Entity("ClrKernel.Jobs.JobTriggerState", b =>
                {
                    b.Property<string>("Project")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)")
                        .HasColumnName("project");

                    b.Property<string>("Environment")
                        .HasMaxLength(16)
                        .HasColumnType("nvarchar(16)")
                        .HasColumnName("environment");

                    b.Property<string>("JobName")
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("job_name");

                    b.Property<DateTime>("LastTriggerAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("last_trigger_at");

                    b.HasKey("Project", "Environment", "JobName");

                    b.ToTable("job_trigger_state", (string)null);
                });

            modelBuilder.Entity("ClrKernel.Jobs.ManualRun", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<Guid>("ActorId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("actor_id");

                    b.Property<string>("ActorName")
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)")
                        .HasColumnName("actor_name");

                    b.Property<int>("CellCount")
                        .HasColumnType("int")
                        .HasColumnName("cell_count");

                    b.Property<string>("Cells")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("cells");

                    b.Property<string>("Environment")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("nvarchar(16)")
                        .HasColumnName("environment");

                    b.Property<string>("ErrorSummary")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("error_summary");

                    b.Property<DateTime?>("FinishedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("finished_at");

                    b.Property<string>("NotebookPath")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("notebook_path");

                    b.Property<string>("Outcome")
                        .HasMaxLength(16)
                        .HasColumnType("nvarchar(16)")
                        .HasColumnName("outcome");

                    b.Property<string>("Overrides")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("overrides");

                    b.Property<string>("Project")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)")
                        .HasColumnName("project");

                    b.Property<DateTime>("StartedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("started_at");

                    b.HasKey("Id");

                    b.HasIndex("StartedAt");

                    b.HasIndex("Project", "Environment", "NotebookPath");

                    b.ToTable("manual_runs", (string)null);
                });

            modelBuilder.Entity("ClrKernel.Jobs.ProjectMembership", b =>
                {
                    b.Property<string>("ProjectSlug")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)")
                        .HasColumnName("project");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("user_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(24)
                        .HasColumnType("nvarchar(24)")
                        .HasColumnName("role");

                    b.HasKey("ProjectSlug", "UserId");

                    b.HasIndex("UserId");

                    b.ToTable("project_members", (string)null);
                });

            modelBuilder.Entity("ClrKernel.Jobs.Run", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<string>("ArtifactPath")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("artifact_path");

                    b.Property<int>("Attempt")
                        .HasColumnType("int")
                        .HasColumnName("attempt");

                    b.Property<Guid?>("CausedByRunId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("caused_by_run_id");

                    b.Property<string>("CommitSha")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)")
                        .HasColumnName("commit_sha");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at");

                    b.Property<string>("Environment")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("nvarchar(16)")
                        .HasColumnName("environment");

                    b.Property<string>("ErrorSummary")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("error_summary");

                    b.Property<DateTime?>("FinishedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("finished_at");

                    b.Property<bool>("HadOverrides")
                        .HasColumnType("bit")
                        .HasColumnName("had_overrides");

                    b.Property<string>("JobName")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("job_name");

                    b.Property<string>("LogPath")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("log_path");

                    b.Property<string>("NotebookPath")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("notebook_path");

                    b.Property<string>("Project")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)")
                        .HasColumnName("project");

                    b.Property<DateTime?>("ScheduledFor")
                        .HasColumnType("datetime2")
                        .HasColumnName("scheduled_for");

                    b.Property<DateTime?>("StartedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("started_at");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("nvarchar(16)")
                        .HasColumnName("status");

                    b.Property<string>("Trigger")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("nvarchar(16)")
                        .HasColumnName("trigger_type");

                    b.Property<bool>("WasDirty")
                        .HasColumnType("bit")
                        .HasColumnName("was_dirty");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("Project", "Environment", "JobName");

                    b.ToTable("runs", (string)null);
                });

            modelBuilder.Entity("ClrKernel.Jobs.RunCell", b =>
                {
                    b.Property<Guid>("RunId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("run_id");

                    b.Property<int>("CellIndex")
                        .HasColumnType("int")
                        .HasColumnName("cell_index");

                    b.Property<string>("ErrorSummary")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("error_summary");

                    b.Property<DateTime?>("FinishedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("finished_at");

                    b.Property<string>("SourcePreview")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("source_preview");

                    b.Property<DateTime?>("StartedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("started_at");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("nvarchar(16)")
                        .HasColumnName("status");

                    b.HasKey("RunId", "CellIndex");

                    b.ToTable("run_cells", (string)null);
                });

            modelBuilder.Entity("ClrKernel.Jobs.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at");

                    b.Property<bool>("Disabled")
                        .HasColumnType("bit")
                        .HasColumnName("disabled");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)")
                        .HasColumnName("display_name");

                    b.Property<DateTime?>("LastSeenAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("last_seen_at");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("nvarchar(16)")
                        .HasColumnName("role");

                    b.HasKey("Id");

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("ClrKernel.Jobs.Credential", b =>
                {
                    b.HasOne("ClrKernel.Jobs.User", "User")
                        .WithMany("Credentials")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("ClrKernel.Jobs.ProjectMembership", b =>
                {
                    b.HasOne("ClrKernel.Jobs.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ClrKernel.Jobs.User", b =>
                {
                    b.Navigation("Credentials");
                });
#pragma warning restore 612, 618
        }
    }
}
