// <auto-generated />
using System;
using ClrKernel.Jobs;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace ClrKernel.Jobs.Store.Migrations.Postgres
{
    [DbContext(typeof(PostgresRunsDbContext))]
    [Migration("20260818214553_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ClrKernel.Jobs.JobTriggerState", b =>
                {
                    b.Property<string>("JobName")
                        .HasColumnType("text");

                    b.Property<DateTime>("LastTriggerAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("JobName");

                    b.ToTable("job_trigger_state", (string)null);
                });

            modelBuilder.Entity("ClrKernel.Jobs.Run", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ArtifactPath")
                        .HasColumnType("text");

                    b.Property<int>("Attempt")
                        .HasColumnType("integer");

                    b.Property<Guid?>("CausedByRunId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ErrorSummary")
                        .HasColumnType("text");

                    b.Property<DateTime?>("FinishedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("JobName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("LogPath")
                        .HasColumnType("text");

                    b.Property<string>("NotebookPath")
                        .HasColumnType("text");

                    b.Property<DateTime?>("ScheduledFor")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("StartedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Trigger")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("JobName");

                    b.ToTable("runs", (string)null);
                });

            modelBuilder.Entity("ClrKernel.Jobs.RunCell", b =>
                {
                    b.Property<Guid>("RunId")
                        .HasColumnType("uuid");

                    b.Property<int>("CellIndex")
                        .HasColumnType("integer");

                    b.Property<string>("ErrorSummary")
                        .HasColumnType("text");

                    b.Property<DateTime?>("FinishedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("SourcePreview")
                        .HasColumnType("text");

                    b.Property<DateTime?>("StartedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("RunId", "CellIndex");

                    b.ToTable("run_cells", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
