// <auto-generated />
using System;
using ClrKernel.Jobs;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace ClrKernel.Jobs.Store.Migrations.Postgres
{
    [DbContext(typeof(PostgresRunsDbContext))]
    partial class PostgresRunsDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ClrKernel.Jobs.JobTriggerState", b =>
                {
                    b.Property<string>("Environment")
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("environment");

                    b.Property<string>("JobName")
                        .HasColumnType("text")
                        .HasColumnName("job_name");

                    b.Property<DateTime>("LastTriggerAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_trigger_at");

                    b.HasKey("Environment", "JobName");

                    b.ToTable("job_trigger_state", (string)null);
                });

            modelBuilder.Entity("ClrKernel.Jobs.Run", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("ArtifactPath")
                        .HasColumnType("text")
                        .HasColumnName("artifact_path");

                    b.Property<int>("Attempt")
                        .HasColumnType("integer")
                        .HasColumnName("attempt");

                    b.Property<Guid?>("CausedByRunId")
                        .HasColumnType("uuid")
                        .HasColumnName("caused_by_run_id");

                    b.Property<string>("CommitSha")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("commit_sha");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Environment")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("environment");

                    b.Property<string>("ErrorSummary")
                        .HasColumnType("text")
                        .HasColumnName("error_summary");

                    b.Property<DateTime?>("FinishedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("finished_at");

                    b.Property<bool>("HadOverrides")
                        .HasColumnType("boolean")
                        .HasColumnName("had_overrides");

                    b.Property<string>("JobName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("job_name");

                    b.Property<string>("LogPath")
                        .HasColumnType("text")
                        .HasColumnName("log_path");

                    b.Property<string>("NotebookPath")
                        .HasColumnType("text")
                        .HasColumnName("notebook_path");

                    b.Property<DateTime?>("ScheduledFor")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("scheduled_for");

                    b.Property<DateTime?>("StartedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("started_at");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("status");

                    b.Property<string>("Trigger")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("trigger_type");

                    b.Property<bool>("WasDirty")
                        .HasColumnType("boolean")
                        .HasColumnName("was_dirty");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("Environment", "JobName");

                    b.ToTable("runs", (string)null);
                });

            modelBuilder.Entity("ClrKernel.Jobs.RunCell", b =>
                {
                    b.Property<Guid>("RunId")
                        .HasColumnType("uuid")
                        .HasColumnName("run_id");

                    b.Property<int>("CellIndex")
                        .HasColumnType("integer")
                        .HasColumnName("cell_index");

                    b.Property<string>("ErrorSummary")
                        .HasColumnType("text")
                        .HasColumnName("error_summary");

                    b.Property<DateTime?>("FinishedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("finished_at");

                    b.Property<string>("SourcePreview")
                        .HasColumnType("text")
                        .HasColumnName("source_preview");

                    b.Property<DateTime?>("StartedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("started_at");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("status");

                    b.HasKey("RunId", "CellIndex");

                    b.ToTable("run_cells", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
