// <auto-generated />
using System;
using ClrKernel.Jobs;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ClrKernel.Jobs.Store.Migrations.Sqlite;

[DbContext(typeof(SqliteRunsDbContext))]
[Migration("20260824225032_AddConnectionQueries")]
partial class AddConnectionQueries
{
    /// <inheritdoc />
    protected override void BuildTargetModel(ModelBuilder modelBuilder)
    {
#pragma warning disable 612, 618
        modelBuilder.HasAnnotation("ProductVersion", "9.0.9");

        modelBuilder.Entity("ClrKernel.Jobs.AuthSession", b =>
            {
                b.Property<string>("Id")
                    .HasMaxLength(64)
                    .HasColumnType("TEXT")
                    .HasColumnName("id");

                b.Property<DateTime>("CreatedAt")
                    .HasColumnType("TEXT")
                    .HasColumnName("created_at");

                b.Property<DateTime>("ExpiresAt")
                    .HasColumnType("TEXT")
                    .HasColumnName("expires_at");

                b.Property<DateTime>("LastSeenAt")
                    .HasColumnType("TEXT")
                    .HasColumnName("last_seen_at");

                b.Property<Guid>("UserId")
                    .HasColumnType("TEXT")
                    .HasColumnName("user_id");

                b.HasKey("Id");

                b.HasIndex("UserId");

                b.ToTable("sessions", (string)null);
            });

        modelBuilder.Entity("ClrKernel.Jobs.Credential", b =>
            {
                b.Property<string>("Id")
                    .HasMaxLength(512)
                    .HasColumnType("TEXT")
                    .HasColumnName("id");

                b.Property<Guid>("AaGuid")
                    .HasColumnType("TEXT")
                    .HasColumnName("aaguid");

                b.Property<DateTime>("CreatedAt")
                    .HasColumnType("TEXT")
                    .HasColumnName("created_at");

                b.Property<DateTime?>("LastUsedAt")
                    .HasColumnType("TEXT")
                    .HasColumnName("last_used_at");

                b.Property<string>("Name")
                    .HasMaxLength(120)
                    .HasColumnType("TEXT")
                    .HasColumnName("name");

                b.Property<byte[]>("PublicKey")
                    .IsRequired()
                    .HasColumnType("BLOB")
                    .HasColumnName("public_key");

                b.Property<long>("SignCount")
                    .HasColumnType("INTEGER")
                    .HasColumnName("sign_count");

                b.Property<string>("Transports")
                    .HasMaxLength(128)
                    .HasColumnType("TEXT")
                    .HasColumnName("transports");

                b.Property<Guid>("UserId")
                    .HasColumnType("TEXT")
                    .HasColumnName("user_id");

                b.HasKey("Id");

                b.HasIndex("UserId");

                b.ToTable("credentials", (string)null);
            });

        modelBuilder.Entity("ClrKernel.Jobs.Invite", b =>
            {
                b.Property<string>("Code")
                    .HasMaxLength(64)
                    .HasColumnType("TEXT")
                    .HasColumnName("code");

                b.Property<DateTime>("CreatedAt")
                    .HasColumnType("TEXT")
                    .HasColumnName("created_at");

                b.Property<Guid?>("CreatedBy")
                    .HasColumnType("TEXT")
                    .HasColumnName("created_by");

                b.Property<DateTime>("ExpiresAt")
                    .HasColumnType("TEXT")
                    .HasColumnName("expires_at");

                b.Property<string>("Label")
                    .HasMaxLength(200)
                    .HasColumnType("TEXT")
                    .HasColumnName("label");

                b.Property<bool>("Revoked")
                    .HasColumnType("INTEGER")
                    .HasColumnName("revoked");

                b.Property<string>("Role")
                    .IsRequired()
                    .HasMaxLength(16)
                    .HasColumnType("TEXT")
                    .HasColumnName("role");

                b.Property<DateTime?>("UsedAt")
                    .HasColumnType("TEXT")
                    .HasColumnName("used_at");

                b.Property<Guid?>("UsedBy")
                    .HasColumnType("TEXT")
                    .HasColumnName("used_by");

                b.HasKey("Code");

                b.ToTable("invites", (string)null);
            });

        modelBuilder.Entity("ClrKernel.Jobs.JobTriggerState", b =>
            {
                b.Property<string>("Project")
                    .HasMaxLength(64)
                    .HasColumnType("TEXT")
                    .HasColumnName("project");

                b.Property<string>("Environment")
                    .HasMaxLength(16)
                    .HasColumnType("TEXT")
                    .HasColumnName("environment");

                b.Property<string>("JobName")
                    .HasColumnType("TEXT")
                    .HasColumnName("job_name");

                b.Property<DateTime>("LastTriggerAt")
                    .HasColumnType("TEXT")
                    .HasColumnName("last_trigger_at");

                b.HasKey("Project", "Environment", "JobName");

                b.ToTable("job_trigger_state", (string)null);
            });

        modelBuilder.Entity("ClrKernel.Jobs.ManualRun", b =>
            {
                b.Property<Guid>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("TEXT")
                    .HasColumnName("id");

                b.Property<Guid>("ActorId")
                    .HasColumnType("TEXT")
                    .HasColumnName("actor_id");

                b.Property<string>("ActorName")
                    .HasMaxLength(120)
                    .HasColumnType("TEXT")
                    .HasColumnName("actor_name");

                b.Property<int>("CellCount")
                    .HasColumnType("INTEGER")
                    .HasColumnName("cell_count");

                b.Property<string>("Cells")
                    .HasColumnType("TEXT")
                    .HasColumnName("cells");

                b.Property<string>("Environment")
                    .IsRequired()
                    .HasMaxLength(16)
                    .HasColumnType("TEXT")
                    .HasColumnName("environment");

                b.Property<string>("ErrorSummary")
                    .HasColumnType("TEXT")
                    .HasColumnName("error_summary");

                b.Property<DateTime?>("FinishedAt")
                    .HasColumnType("TEXT")
                    .HasColumnName("finished_at");

                b.Property<string>("NotebookPath")
                    .IsRequired()
                    .HasColumnType("TEXT")
                    .HasColumnName("notebook_path");

                b.Property<string>("Outcome")
                    .HasMaxLength(16)
                    .HasColumnType("TEXT")
                    .HasColumnName("outcome");

                b.Property<string>("Overrides")
                    .HasColumnType("TEXT")
                    .HasColumnName("overrides");

                b.Property<string>("Project")
                    .IsRequired()
                    .HasMaxLength(64)
                    .HasColumnType("TEXT")
                    .HasColumnName("project");

                b.Property<DateTime>("StartedAt")
                    .HasColumnType("TEXT")
                    .HasColumnName("started_at");

                b.HasKey("Id");

                b.HasIndex("StartedAt");

                b.HasIndex("Project", "Environment", "NotebookPath");

                b.ToTable("manual_runs", (string)null);
            });

        modelBuilder.Entity("ClrKernel.Jobs.ProjectMembership", b =>
            {
                b.Property<string>("ProjectSlug")
                    .HasMaxLength(64)
                    .HasColumnType("TEXT")
                    .HasColumnName("project");

                b.Property<Guid>("UserId")
                    .HasColumnType("TEXT")
                    .HasColumnName("user_id");

                b.Property<DateTime>("CreatedAt")
                    .HasColumnType("TEXT")
                    .HasColumnName("created_at");

                b.Property<string>("Role")
                    .IsRequired()
                    .HasMaxLength(24)
                    .HasColumnType("TEXT")
                    .HasColumnName("role");

                b.HasKey("ProjectSlug", "UserId");

                b.HasIndex("UserId");

                b.ToTable("project_members", (string)null);
            });

        modelBuilder.Entity("ClrKernel.Jobs.QueryAudit", b =>
            {
                b.Property<Guid>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("TEXT")
                    .HasColumnName("id");

                b.Property<Guid>("ActorId")
                    .HasColumnType("TEXT")
                    .HasColumnName("actor_id");

                b.Property<string>("ActorName")
                    .HasMaxLength(120)
                    .HasColumnType("TEXT")
                    .HasColumnName("actor_name");

                b.Property<string>("ConnectionId")
                    .IsRequired()
                    .HasMaxLength(64)
                    .HasColumnType("TEXT")
                    .HasColumnName("connection_id");

                b.Property<string>("ConnectionName")
                    .HasMaxLength(200)
                    .HasColumnType("TEXT")
                    .HasColumnName("connection_name");

                b.Property<double>("DurationMs")
                    .HasColumnType("REAL")
                    .HasColumnName("duration_ms");

                b.Property<string>("ErrorSummary")
                    .HasColumnType("TEXT")
                    .HasColumnName("error_summary");

                b.Property<bool>("LeastPrivilege")
                    .HasColumnType("INTEGER")
                    .HasColumnName("least_privilege");

                b.Property<string>("Outcome")
                    .HasMaxLength(16)
                    .HasColumnType("TEXT")
                    .HasColumnName("outcome");

                b.Property<int>("RowsAffected")
                    .HasColumnType("INTEGER")
                    .HasColumnName("rows_affected");

                b.Property<DateTime>("StartedAt")
                    .HasColumnType("TEXT")
                    .HasColumnName("started_at");

                b.Property<string>("Statement")
                    .HasColumnType("TEXT")
                    .HasColumnName("statement");

                b.HasKey("Id");

                b.HasIndex("ConnectionId");

                b.HasIndex("StartedAt");

                b.ToTable("connection_queries", (string)null);
            });

        modelBuilder.Entity("ClrKernel.Jobs.Run", b =>
            {
                b.Property<Guid>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("TEXT")
                    .HasColumnName("id");

                b.Property<string>("ArtifactPath")
                    .HasColumnType("TEXT")
                    .HasColumnName("artifact_path");

                b.Property<int>("Attempt")
                    .HasColumnType("INTEGER")
                    .HasColumnName("attempt");

                b.Property<Guid?>("CausedByRunId")
                    .HasColumnType("TEXT")
                    .HasColumnName("caused_by_run_id");

                b.Property<string>("CommitSha")
                    .HasMaxLength(64)
                    .HasColumnType("TEXT")
                    .HasColumnName("commit_sha");

                b.Property<DateTime>("CreatedAt")
                    .HasColumnType("TEXT")
                    .HasColumnName("created_at");

                b.Property<string>("Environment")
                    .IsRequired()
                    .HasMaxLength(16)
                    .HasColumnType("TEXT")
                    .HasColumnName("environment");

                b.Property<string>("ErrorSummary")
                    .HasColumnType("TEXT")
                    .HasColumnName("error_summary");

                b.Property<DateTime?>("FinishedAt")
                    .HasColumnType("TEXT")
                    .HasColumnName("finished_at");

                b.Property<bool>("HadOverrides")
                    .HasColumnType("INTEGER")
                    .HasColumnName("had_overrides");

                b.Property<string>("JobName")
                    .IsRequired()
                    .HasColumnType("TEXT")
                    .HasColumnName("job_name");

                b.Property<string>("LogPath")
                    .HasColumnType("TEXT")
                    .HasColumnName("log_path");

                b.Property<string>("NotebookPath")
                    .HasColumnType("TEXT")
                    .HasColumnName("notebook_path");

                b.Property<string>("Project")
                    .IsRequired()
                    .HasMaxLength(64)
                    .HasColumnType("TEXT")
                    .HasColumnName("project");

                b.Property<DateTime?>("ScheduledFor")
                    .HasColumnType("TEXT")
                    .HasColumnName("scheduled_for");

                b.Property<DateTime?>("StartedAt")
                    .HasColumnType("TEXT")
                    .HasColumnName("started_at");

                b.Property<string>("Status")
                    .IsRequired()
                    .HasMaxLength(16)
                    .HasColumnType("TEXT")
                    .HasColumnName("status");

                b.Property<string>("Trigger")
                    .IsRequired()
                    .HasMaxLength(16)
                    .HasColumnType("TEXT")
                    .HasColumnName("trigger_type");

                b.Property<bool>("WasDirty")
                    .HasColumnType("INTEGER")
                    .HasColumnName("was_dirty");

                b.HasKey("Id");

                b.HasIndex("CreatedAt");

                b.HasIndex("Project", "Environment", "JobName");

                b.ToTable("runs", (string)null);
            });

        modelBuilder.Entity("ClrKernel.Jobs.RunCell", b =>
            {
                b.Property<Guid>("RunId")
                    .HasColumnType("TEXT")
                    .HasColumnName("run_id");

                b.Property<int>("CellIndex")
                    .HasColumnType("INTEGER")
                    .HasColumnName("cell_index");

                b.Property<string>("ErrorSummary")
                    .HasColumnType("TEXT")
                    .HasColumnName("error_summary");

                b.Property<DateTime?>("FinishedAt")
                    .HasColumnType("TEXT")
                    .HasColumnName("finished_at");

                b.Property<string>("SourcePreview")
                    .HasColumnType("TEXT")
                    .HasColumnName("source_preview");

                b.Property<DateTime?>("StartedAt")
                    .HasColumnType("TEXT")
                    .HasColumnName("started_at");

                b.Property<string>("Status")
                    .IsRequired()
                    .HasMaxLength(16)
                    .HasColumnType("TEXT")
                    .HasColumnName("status");

                b.HasKey("RunId", "CellIndex");

                b.ToTable("run_cells", (string)null);
            });

        modelBuilder.Entity("ClrKernel.Jobs.User", b =>
            {
                b.Property<Guid>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("TEXT")
                    .HasColumnName("id");

                b.Property<DateTime>("CreatedAt")
                    .HasColumnType("TEXT")
                    .HasColumnName("created_at");

                b.Property<bool>("Disabled")
                    .HasColumnType("INTEGER")
                    .HasColumnName("disabled");

                b.Property<string>("DisplayName")
                    .IsRequired()
                    .HasMaxLength(120)
                    .HasColumnType("TEXT")
                    .HasColumnName("display_name");

                b.Property<DateTime?>("LastSeenAt")
                    .HasColumnType("TEXT")
                    .HasColumnName("last_seen_at");

                b.Property<string>("Role")
                    .IsRequired()
                    .HasMaxLength(16)
                    .HasColumnType("TEXT")
                    .HasColumnName("role");

                b.HasKey("Id");

                b.ToTable("users", (string)null);
            });

        modelBuilder.Entity("ClrKernel.Jobs.Credential", b =>
            {
                b.HasOne("ClrKernel.Jobs.User", "User")
                    .WithMany("Credentials")
                    .HasForeignKey("UserId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();

                b.Navigation("User");
            });

        modelBuilder.Entity("ClrKernel.Jobs.ProjectMembership", b =>
            {
                b.HasOne("ClrKernel.Jobs.User", null)
                    .WithMany()
                    .HasForeignKey("UserId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();
            });

        modelBuilder.Entity("ClrKernel.Jobs.User", b =>
            {
                b.Navigation("Credentials");
            });
#pragma warning restore 612, 618
    }
}
